import { routeQuestion } from "./intent";

/**
 * Follow-up questions, written from the answer the reader just got.
 *
 * They were a fixed list per template, which is why every tafsīr answer offered
 * «ما سبب نزول هذه الآية؟» whether or not the answer had already covered it,
 * and why they said «هذه الآية» rather than naming it. A follow-up is only
 * worth offering if it is the next thing *this* answer leaves open.
 *
 * Generated by a cheap model rather than by the answering one: it is a separate
 * job from writing the answer, it must not delay the first token, and a run
 * that fails should cost the reader a suggestion rather than an answer.
 */

/** Four at most. A list longer than that is a menu, not a suggestion. */
export const MAX_FOLLOW_UPS = 4;

const MODEL = "gpt-4.1-mini";

const INSTRUCTIONS = `أنت تقترح أسئلة متابعة بعد إجابة شرعية.

اقترح حتى أربعة أسئلة، كل سؤال في سطر مستقل، دون ترقيم ولا رموز ولا أي نص آخر.

قواعد:
- اكتب السؤال كما يكتبه القارئ نفسه: قصير، مباشر، بالعربية الفصيحة.
- اجعله خطوة تالية حقيقية: ما تركته الإجابة مفتوحًا، لا ما أجابت عنه فعلًا.
- سمِّ ما تسأل عنه صراحةً — «ما سبب نزول آية النحل 43؟» لا «ما سبب نزول هذه الآية؟» — فقد يُقرأ السؤال بعيدًا عن سياقه.
- اقتصر على ما يمكن الإجابة عنه من كتب التفسير والحديث والفقه المعتمدة.
- **لا تقترح سؤالًا عن حالة شخصية** («هل يجوز لي…»، «ماذا أفعل إن…»)، فالنظام لا يُفتي في الحالات الخاصة.
- لا تقترح سؤالًا يطلب ترجيحًا بين أقوال العلماء.
- إن لم يكن ثَمّ متابعة مفيدة، فلا تكتب شيئًا.`;

/**
 * One question per line, with the personal-case ones dropped.
 *
 * The instructions ask for this; the filter makes it certain. A suggested
 * question is a button the reader will press, so offering «هل يجوز لي…؟» walks
 * them into the one thing the system must not do — and it would be answered
 * with a referral, which is a poor use of a suggestion. Same reasoning as
 * enforcing the source allow-list rather than instructing it.
 */
const parse = (text: string) =>
  text
    .split("\n")
    .map((line) =>
      line
        // strip a bullet or a number if one slipped through
        .replace(/^\s*(?:[-*•]|\d+[.)])\s*/, "")
        .trim(),
    )
    .filter((line) => line.length >= 6 && line.length <= 120)
    .filter((line) => routeQuestion(line).level !== "d")
    .slice(0, MAX_FOLLOW_UPS);

/**
 * Suggests what to ask next.
 *
 * Returns an empty list rather than throwing: a missing suggestion is a missing
 * convenience, and the answer above it is unaffected.
 */
export const generateFollowUps = async (
  question: string,
  answer: string,
  apiKey?: string,
): Promise<string[]> => {
  if (!apiKey || !answer.trim()) return [];

  try {
    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: MODEL,
        instructions: INSTRUCTIONS,
        // the answer is truncated: the opening carries what it covered, and the
        // whole of a long answer costs tokens without changing the suggestions
        input: `السؤال: ${question}\n\nالإجابة:\n${answer.slice(0, 4000)}`,
        temperature: 0.4,
      }),
      signal: AbortSignal.timeout(15_000),
    });
    if (!response.ok) return [];

    const payload = (await response.json()) as {
      output?: { type?: string; content?: { text?: string }[] }[];
    };
    const text = (payload.output ?? [])
      .filter((item) => item.type === "message")
      .flatMap((item) => item.content ?? [])
      .map((content) => content.text ?? "")
      .join("");

    return parse(text);
  } catch {
    return [];
  }
};
